#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  6 12:50:04 2019

@author: ai
"""

grid = [[2,1,1],
         [1,1,0],
         [0,1,1]]


R, C = len(grid), len(grid[0])















[[2, 2, 1], 
 [2, 2, 0], 
 [0, 1, 1]]

#[[2, 2, 1], 
# [2, 2, 0], 
# [0, 2, 1]]

for line in range(len(inputi)-1):
    line1 = inputi[line]
    line2 = inputi[line+1]
    
    line_new = line1[:]
    line_new_h = line1[:]
    for v in range(len(line1)-1):
        if line_new[v] == 2 and line_new[v + 1] != 0:
            line_new_h[v + 1] = 2
            print(line_new)
            print(line_new_h)
    
    line_new_v = inputi[:]
    line1_v = line_new_v[line]
    print(line1_v)
    line2_v = line_new_v[line+1]
    print(line2_v)
    changed_line2 = line2[:]
    print(changed_line2)
    for v_v in range(len(inputi)-1):
        print(line1_v[v_v])
        print(line2_v[v_v])
        if line1_v[v_v] == 2 and line2_v[v_v] != 0:
            changed_line2[v_v] = 2
            print(changed_line2)
            print(line2)
            
        
    
    
    inputi[line] = line_new_h
    inputi[line+1] = changed_line2
    print(inputi)
            